version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: roger8b/nginx
    container_name: nginx
    ports:
      - '80:80'
    networks:
      - production-network
    depends_on:
      - shop

  mysql:
    build:
      dockerfile: ./docker/mysql.dockerfile
      context: .
    env_file: 
      - .env
    image: roger8b/mysql
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - production-network

  shop:
    build:
      dockerfile: ./docker/shop.dockerfile
      context: .
    image: roger8b/shop
    container_name: shop
    ports:
      - 3000
    networks:
      - production-network
    depends_on:
      - mysql

networks:
  production-network:
    driver: bridge
volumes:
  db-volume:
